[versions."3.1.0".local-images]
java-devel = "21"
jdk-base = "21"
"opensearch/security-plugin" = "3.1.0.0"
"opensearch/opensearch-prometheus-exporter" = "3.1.0.0"

[versions."3.1.0".build-arguments]
"opensearch-alerting-plugin-version" = "3.1.0.0"
"opensearch-anomaly-detection-plugin-version" = "3.1.0.0"
"opensearch-asynchronous-search-plugin-version" = "3.1.0.0"
"opensearch-cross-cluster-replication-plugin-version" = "3.1.0.0"
"opensearch-custom-codecs-plugin-version" = "3.1.0.0"
"opensearch-flow-framework-plugin-version" = "3.1.0.0"
"opensearch-geospatial-plugin-version" = "3.1.0.0"
"opensearch-index-management-plugin-version" = "3.1.0.0"
"opensearch-job-scheduler-plugin-version" = "3.1.0.0"
"opensearch-knn-plugin-version" = "3.1.0.0"
"opensearch-ml-plugin-version" = "3.1.0.0"
"opensearch-neural-search-plugin-version" = "3.1.0.0"
"opensearch-notifications-plugin-version" = "3.1.0.0"
"opensearch-notifications-core-plugin-version" = "3.1.0.0"
"opensearch-observability-plugin-version" = "3.1.0.0"
"opensearch-performance-analyzer-plugin-version" = "3.1.0.0"
"opensearch-reports-scheduler-plugin-version" = "3.1.0.0"
"opensearch-search-relevance-plugin-version" = "3.1.0.0"
"opensearch-security-plugin-version" = "3.1.0.0"
"opensearch-security-analytics-plugin-version" = "3.1.0.0"
"opensearch-skills-plugin-version" = "3.1.0.0"
"opensearch-sql-plugin-version" = "3.1.0.0"
"opensearch-system-templates-plugin-version" = "3.1.0.0"
"opensearch-ubi-plugin-version" = "3.1.0.0"
"query-insights-plugin-version" = "3.1.0.0"
