[package]
name = "patchable"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
git2.workspace = true
regex.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
