---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: simple-opa
spec:
  image:
    productVersion: "0.67.1"
  clusterConfig:
    userInfo: 
      backend:
        keycloak:
          hostname: keycloak.default.svc.cluster.local
          port: 80
          tls:
            verification:
              server:
                caCert:
                  secretClass: tls 
          clientCredentialsSecret: user-info-fetcher-client-credentials 
          adminRealm: master 
          userRealm: master 
  servers:
    config:
      logging:
        containers:
          opa:
            loggers:
              decision:
                level: INFO
    roleGroups:
      default: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-info-fetcher-client-credentials
stringData:
  clientId: user-info-fetcher 
  clientSecret: JduWbQyTt40sFwPUxVjYZjiDQCZzaTnC 
