---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  annotations: {
    ""
  }
spec:
  image:
    custom: docker.stackable.tech/sandbox/superset:4.0.2-stackable0.0.0-dev-opaV2
    productVersion: 4.0.2
    pullPolicy: Never
  clusterConfig:
    credentialsSecret: simple-superset-credentials
    listenerClass: external-unstable
    authorization:
      opa:
        configMapName: simple-opa
        package: superset
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
    # podOverrides:
      # spec:
        # containers:
        # - name: superset
          # env:
          # - name: STACKABLE_OPA_ENDPOINT
            # valueFrom:
              # configMapKeyRef:
                # key: OPA
                # name: simple-opa
                #envOverrides:         
                #AUTH_USER_REGISTRATION_ROLE: Gamma
    configOverrides:
      superset_config.py:
        # EXPERIMENTAL_FILE_HEADER: |
        #  from superset.security.manager import OpaSupersetSecurityManager
        # Maybe also ENABLE_TEMPLATE_PROCESSING
        FEATURE_FLAGS: |-
          {
            'ENABLE_JAVASCRIPT_CONTROLS': True,
            'ALERT_REPORTS': True,
            'EMBEDDED_SUPERSET': True,
            'DASHBOARD_RBAC': True,
            'HORIZONTAL_FILTER_BAR': True
          }
        BABEL_DEFAULT_LOCALE: '"de"'          
        LANGUAGES: |-
          {
            "de": {"flag": "de", "name": "Deutsch"},
            "en": {"flag": "us", "name": "English"}
          }
        GUEST_ROLE_NAME: |-
          "Gamma"
        CORS_OPTIONS: |-
          {
            'supports_credentials': True,
            'allow_headers': ['*'],
            'resources':['*'],
            'origins': ['*']
          }
        SESSION_COOKIE_SECURE: |-
          {
            False
          }
        WTF_CSRF_ENABLED: |-
          {
            False
          }
        # TODO: Add these line with superset operator
        # CUSTOM_SECURITY_MANAGER: OpaSupersetSecurityManager
        # AUTH_USER_REGISTRATION_ROLE: os.getenv('AUTH_USER_REGISTRATION_ROLE', 'Public')
        # STACKABLE_OPA_ENDPOINT: os.getenv('STACKABLE_OPA_ENDPOINT')
        # STACKABLE_OPA_PACKAGE: |-
          # "superset"
        # STACKABLE_OPA_RULE: os.getenv('STACKABLE_OPA_RULE', 'user_roles')
