[bump]
# We set this to false, because we currently use a 0.X.X version. Features will thus only bump the
# patch-level version.
features_always_bump_minor = false

# We set this to false, because we currently use a 0.X.X version. Breaking changes will thus only
# bump the minor version.
breaking_always_bump_major = false

initial_tag = "0.1.0"

[git]
# All commits should be parsed as conventional commits.
conventional_commits = true

# All unconventional commits are filtered out and ignored.
filter_unconventional = true

# Commits listed in the changelog are sorted from newest to oldest.
sort_commits = "newest"

# Filter and ignore all commits NOT matched by the commit parsers below.
filter_commits = true

commit_parsers = [
  { message = "^feat\\(boil\\)", group = "<!-- 0 --> Features" },
  { message = "^fix\\(boil\\)", group = "<!-- 1 --> Bug Fixes" },
  { message = "^docs?\\(boil\\)", group = "<!-- 2 --> Documentation" },
  { message = "^(perf|refactor|test)\\(boil\\)", group = "<!-- 3 --> Improvements" },
  { message = "^chore\\(boil\\): Improve", group = "<!-- 3 --> Improvements" },
  { message = "^chore\\(boil\\)", group = "<!-- 4 --> Miscellaneous" },
  { message = "^chore\\(boil\\): Release", skip = true },
]

commit_preprocessors = [
  # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/pull/${2}))" },
]

# Only consider the 'boil-' Git tags when generating the changelog
tag_pattern = "boil-[0-9]*.[0-9]*.[0-9]*"

# Ignore the first release tag
skip_tags = "boil-0.1.0"

[changelog]
trim = true

postprocessors = [
  # Replace the placeholder `<REPO>` with a URL.
  { pattern = '<REPO>', replace = "https://github.com/stackabletech/docker-images" },
]

header = """<!-- GENERATED BY GIT-CLIFF, DO NOT EDIT MANUALLY -->

# Changelog

All notable changes to this project will be documented in this file.

"""

body = """
{% if version %}\
    {% if previous.version %}\
        ## [[{{ version | trim_start_matches(pat="boil-") }}]\
          (<REPO>/compare/{{ previous.version }}..{{ version }})] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="boil-") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}**BREAKING:** {% endif %}{{ commit.message | upper_first -}}.
    {% endfor %}
{% endfor %}\
"""

footer = "<!-- GENERATED BY GIT-CLIFF, DO NOT EDIT MANUALLY -->"
