#!/usr/bin/env bash
# Run this to generate the badges table for the dev workflows.
# You will need to copy/paste the table at the top of the readme, and the links
# at the end of the readme.

AUTO_GENERATED_COMMENT="<!-- autogenerated by $0 -->"
GITHUB_ACTION_URL_PREFIX="https://github.com/stackabletech/docker-images/actions/workflows"
COLS=4

# https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml/badge.svg
# https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml

# [![Build Airflow](https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml/badge.svg)](https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml)

LINK_SHORTCUTS=()
CURRENT_COLUMN=-1

echo $AUTO_GENERATED_COMMENT

# Print the empty headings
for i in $(seq 0 $(($COLS - 1))); do
  echo -n "| "
done
echo "|"

# Print the heading separator and alignments
for i in $(seq 0 $(($COLS - 1))); do
  echo -n "| -: "
done
echo "|"

for DEV_WORKFLOW_FILE in .github/workflows/dev_*.yaml; do
  CURRENT_COLUMN=$(( (${CURRENT_COLUMN} + 1) % ${COLS} ))

  DEV_WORKFLOW_NAME="$(yq -r '.name' $DEV_WORKFLOW_FILE)"
  DEV_WORKFLOW_BASENAME="$(basename $DEV_WORKFLOW_FILE)"
  DEV_WORKFLOW_WORKFLOW_URL="${GITHUB_ACTION_URL_PREFIX}/${DEV_WORKFLOW_BASENAME}"
  DEV_WORKFLOW_BADGE_URL="${DEV_WORKFLOW_WORKFLOW_URL}/badge.svg"

  # Append the image and link shortcuts to be printed at the end
  LINK_SHORTCUTS+=("[${DEV_WORKFLOW_NAME}]: ${DEV_WORKFLOW_BADGE_URL}")
  LINK_SHORTCUTS+=("[${DEV_WORKFLOW_BASENAME}]: ${DEV_WORKFLOW_WORKFLOW_URL}")

  # Print the cells which contain the shortcuts to the image and link:
  # eg: [![Build Airflow]][dev_airflow.yaml]
  echo -n "| [![${DEV_WORKFLOW_NAME}]][${DEV_WORKFLOW_BASENAME}] "
  # Use this for debugging the grid (comment out the echo above):
  # echo -n "| x "

  # On the last column, cap it off
  if [ ${CURRENT_COLUMN} -eq $(( ${COLS} - 1 )) ]; then
    echo -n "|"
    echo
  fi
done
echo

# Print the image and link shortcuts. Eg:
# [Build Airflow]: https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml/badge.svg
# [dev_airflow.yaml]: https://github.com/stackabletech/docker-images/actions/workflows/dev_airflow.yaml
echo $AUTO_GENERATED_COMMENT
printf '%s\n' "${LINK_SHORTCUTS[@]}"

