[versions."2.6.1".local-images]
"hadoop/hadoop" = "3.3.6"
java-base = "11"
java-devel = "11"

[versions."2.6.1".build-arguments]
async-profiler-version = "2.9"
delete-caches = "true"

[versions."2.6.2".local-images]
"hadoop/hadoop" = "3.4.1"
java-base = "11"
java-devel = "11"

[versions."2.6.2".build-arguments]
async-profiler-version = "2.9"
delete-caches = "true"
