---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
spec:
  containers:
    - name: zookeeper
      image: zookeeper-test:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: config-volume
        mountPath: /stackable/zookeeper/conf
      #- name: id-volume
      #  mountPath: /stackable/zookeeper/data
      - name: data-volume
        mountPath: /stackable/zookeeper/data
  volumes:
    - name: config-volume
      configMap:
        name: zookeeper-config
    #- name: id-volume
    #  configMap:
    #  name: zookeeper-myid
    - name: data-volume
      emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: default
data:
  zoo.cfg: |
    # The number of milliseconds of each tick
    tickTime=2000
    # The number of ticks that the initial
    # synchronization phase can take
    initLimit=10
    # The number of ticks that can pass between
    # sending a request and getting an acknowledgement
    syncLimit=5
    # the directory where the snapshot is stored.
    # do not use /tmp for storage, /tmp here is just
    # example sakes.
    dataDir=/etc/stackable/zookeeper-3.5.8/data
    # the port at which the clients will connect
    clientPort=2181
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-myid
  namespace: default
data:
  myid: |
    1
