[metadata.registries]
"oci.stackable.tech" = { namespace = "sdp" }

# Deprecated since 26.7
[versions."30.0.1".local-images]
# https://druid.apache.org/docs/30.0.1/operations/java/
java-base = "17"
java-devel = "17"
"hadoop/hadoop" = "3.3.6"

[versions."30.0.1".build-arguments]
authorizer-version = "0.7.0"

# Deprecated since 26.7
[versions."35.0.1".local-images]
# https://druid.apache.org/docs/35.0.1/operations/java/
java-base = "21"
java-devel = "21"
"hadoop/hadoop" = "3.4.3"

[versions."35.0.1".build-arguments]
authorizer-version = "0.7.0"

# LTS since 26.7
[versions."37.0.0".local-images]
# https://druid.apache.org/docs/37.0.0/operations/java/
java-base = "21"
java-devel = "21"
"hadoop/hadoop" = "3.4.3"

[versions."37.0.0".build-arguments]
# We don't need to bump this if no code changed in https://github.com/stackabletech/druid-opa-authorizer
# But a PR still needs to be raised to add/remove versions and ensure it still builds.

# IMHO this is a mess. We fetch the release from https://repo.stackable.tech/repository/packages/druid/druid-opa-authorizer-${AUTHORIZER_VERSION}.tar.gz
# and use that. There hasn't been a release since 2025-06-02. It's a random .tar.gz of a .jar file in Nexus.
# It was compiled against
#
# * A totally different Druid version
# * Different jackson version
# * Different guava version
# * Different guice version
# * Different Java version (this should be fine)
#
# Yes, this seems to have worked in the past, but we should build the authorizer from source (as we
# do with others). It should also require a mandatory profile (no activation by default), so that
# the build fails on an unsupported Druid version.
authorizer-version = "0.7.0"
