---
name: Generate Shards
description: This action builds list of shard indices for use in Github Actions Matrices
inputs:
  product-name:
    description: The name of the product to build via bake (directory name)
    required: true
outputs:
  versions:
    description: A list of product versions
    value: ${{ steps.generate_shards.outputs.VERSIONS }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'
    - name: Generate Shards
      id: generate_shards
      shell: python
      env:
        PRODUCT_NAME: ${{ inputs.product-name }}
      run: |
        # Need to get the list of versions for the product
        import sys
        import os
        sys.path.append(str(os.getcwd()))
        import conf

        product=os.environ['PRODUCT_NAME']
        print(f"Generating version list for {product}")

        # get the product config
        product_conf = list(filter(lambda x: x["name"] == product, conf.products))[0]
        # list the versions, eg: [1.0, 1.1, 2.0]
        versions = [v["product"] for k,v in enumerate(product_conf["versions"])]
        output_versions = f"VERSIONS={versions}\n"

        github_outputs_file = os.environ['GITHUB_OUTPUT']
        f = open(github_outputs_file, "w")
        print(f"Writing to $GITHUB_OUTPUT: {output_versions}")
        f.write(output_versions)
        f.close()
    - name: Print Shards
      shell: bash
      run: |
        set -euo pipefail
        echo versions=${{ steps.generate_shards.outputs.VERSIONS }}
