---
name: Publish Product Image
description: This action publishes a Docker image
inputs:
  product:
    description: The name of the product to publish
    required: true
  nexus-password:
    description: The password to login to Nexus
    required: true
  harbor-secret:
    description: The secret to login to Harbor
    required: true
runs:
  using: composite
  steps:
    - name: Set up Cosign
      uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0

    - name: Set up syft
      uses: anchore/sbom-action/download-syft@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0.16.0

    - name: Login to Stackable Nexus
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        registry: docker.stackable.tech
        username: github
        password: ${{ inputs.nexus-password }}

    - name: Login to Stackable Harbor
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        registry: oci.stackable.tech
        username: robot$sdp+github-action-build
        password: ${{ inputs.harbor-secret }}

    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "bake-target-tags: "$(< bake-target-tags)
        IMAGE_NAME=$(cat bake-target-tags | cut -d ":" -f 1)
        TAG_NAME=$(cat bake-target-tags | cut -d ":" -f 2)
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Push Image to repo.stackable.tech and sign via cosign
      shell: bash
      run: |
        # Store the output of `docker image push` into a variable, so we can
        # parse it for the digest
        PUSH_OUTPUT=$(docker image push "$(< bake-target-tags)" 2>&1)
        echo "$PUSH_OUTPUT"
        # Obtain the digest of the pushed image from the output of `docker image
        # push`, because signing by tag is deprecated and will be removed from
        # cosign in the future
        DIGEST=$(echo "$PUSH_OUTPUT" | awk "/: digest: sha256:[a-f0-9]{64} size: [0-9]+$/ { print \$3 }")
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV
        # Refer to image via its digest (docker.stackable.tech/stackable/airflow@sha256:0a1b2c...)
        # This generates a signature and publishes it to the registry, next to the image
        # Uses the keyless signing flow with Github Actions as identity provider
        cosign sign -y "$IMAGE_NAME@$DIGEST"

    - name: Generate SBOM for the Image
      shell: bash
      run: |
        syft scan --output cyclonedx-json=sbom.json --select-catalogers "-cargo-auditable-binary-cataloger" --scope all-layers --source-name "${{ inputs.product }}" --source-version "$TAG_NAME" "$IMAGE_NAME@$DIGEST";
        # Determine the PURL for the image
        PURL="pkg:docker/stackable/${{ inputs.product }}@$DIGEST?repository_url=docker.stackable.tech";
        # Get metadata from the image
        IMAGE_METADATA_DESCRIPTION=$(docker inspect --format='{{.Config.Labels.description}}' "$IMAGE_NAME@$DIGEST");
        IMAGE_METADATA_NAME=$(docker inspect --format='{{.Config.Labels.name}}' "$IMAGE_NAME@$DIGEST");
        # Merge the SBOM with the metadata for the image
        jq -s '{"metadata":{"component":{"description":"'"$IMAGE_METADATA_NAME. $IMAGE_METADATA_DESCRIPTION"'","supplier":{"name":"Stackable GmbH","url":["https://stackable.tech/"]},"author":"Stackable GmbH","purl":"'"$PURL"'","publisher":"Stackable GmbH"}}} * .[0]' sbom.json > sbom.merged.json;
        # Attest the SBOM to the image
        cosign attest -y --predicate sbom.merged.json --type cyclonedx "$IMAGE_NAME@$DIGEST"

    - name: Push Image to oci.stackable.tech and sign via cosign
      shell: bash
      run: |
        IMAGE_NAME=oci.stackable.tech/sdp/${{ inputs.product }}
        echo "image: $IMAGE_NAME"
        docker tag "$(< bake-target-tags)" "$IMAGE_NAME:$TAG_NAME"
        # Store the output of `docker image push` into a variable, so we can parse it for the digest
        PUSH_OUTPUT=$(docker image push "$IMAGE_NAME:$TAG_NAME" 2>&1)
        echo "$PUSH_OUTPUT"
        # Obtain the digest of the pushed image from the output of `docker image push`, because signing by tag is deprecated and will be removed from cosign in the future
        DIGEST=$(echo "$PUSH_OUTPUT" | awk "/: digest: sha256:[a-f0-9]{64} size: [0-9]+$/ { print \$3 }")
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV
        # Refer to image via its digest (oci.stackable.tech/sdp/airflow@sha256:0a1b2c...)
        # This generates a signature and publishes it to the registry, next to the image
        # Uses the keyless signing flow with Github Actions as identity provider
        cosign sign -y "$IMAGE_NAME@$DIGEST"

    - name: Generate SBOM for the Image
      shell: bash
      run: |
        syft scan --output cyclonedx-json=sbom.json --select-catalogers "-cargo-auditable-binary-cataloger" --scope all-layers --source-name "${{ inputs.product }}" --source-version "$TAG_NAME" "$IMAGE_NAME@$DIGEST";
        # Determine the PURL for the image
        PURL="pkg:docker/sdp/${{ inputs.product }}@$DIGEST?repository_url=oci.stackable.tech";
        # Get metadata from the image
        IMAGE_METADATA_DESCRIPTION=$(docker inspect --format='{{.Config.Labels.description}}' "$IMAGE_NAME@$DIGEST");
        IMAGE_METADATA_NAME=$(docker inspect --format='{{.Config.Labels.name}}' "$IMAGE_NAME@$DIGEST");
        # Merge the SBOM with the metadata for the image
        jq -s '{"metadata":{"component":{"description":"'"$IMAGE_METADATA_NAME. $IMAGE_METADATA_DESCRIPTION"'","supplier":{"name":"Stackable GmbH","url":["https://stackable.tech/"]},"author":"Stackable GmbH","purl":"'"$PURL"'","publisher":"Stackable GmbH"}}} * .[0]' sbom.json > sbom.merged.json;
        # Attest the SBOM to the image
        cosign attest -y --predicate sbom.merged.json --type cyclonedx "$IMAGE_NAME@$DIGEST"

    - name: Create Manifest
      shell: bash
      run: |
        MANIFEST_NAME="docker.stackable.tech/stackable/${{ inputs.product }}:$TAG_NAME-stackable0.0.0-dev"
        # Create and push to Stackable Nexus
        # `docker manifest push` directly returns the digest of the manifest list
        # As it is an experimental feature, this might change in the future
        # Further reading: https://docs.docker.com/reference/cli/docker/manifest/push/
        # --amend because the manifest list would be updated since we use the same tag: 0.0.0-dev
        docker manifest create "$MANIFEST_NAME" --amend "${MANIFEST_NAME}-amd64" --amend "${MANIFEST_NAME}-arm64"
        DIGEST=$(docker manifest push $MANIFEST_NAME)

        # Refer to image via its digest (oci.stackable.tech/sdp/airflow@sha256:0a1b2c...)
        # This generates a signature and publishes it to the registry, next to the image
        # Uses the keyless signing flow with Github Actions as identity provider
        cosign sign -y "$MANIFEST_NAME@$DIGEST"

        # Push to oci.stackable.tech as well
        MANIFEST_NAME="oci.stackable.tech/sdp/${PRODUCT}:${VERSION}-stackable0.0.0-dev"
        docker manifest create "$MANIFEST_NAME" --amend "${MANIFEST_NAME}-amd64" --amend "${MANIFEST_NAME}-arm64"
        DIGEST=$(docker manifest push $MANIFEST_NAME)
        cosign sign -y "$MANIFEST_NAME@$DIGEST"
