#!/bin/bash

if [ $# -ne 3 ] 
    then
    echo "Wrong number of parameters supplied. Usage:"
    echo "$0 <directory> <uid> <gid>"
    echo "$0 /stackable 1000 0"
fi

STACKABLE_DIR=$1
EXPECTED_UID=$2
EXPECTED_GID=$3

error_flag=0

# Check ownership
while IFS= read -r -d '' file; do
    uid=$(stat -c "%u" "$file")
    gid=$(stat -c "%g" "$file")

    if [[ "$uid" -ne "$EXPECTED_UID" || "$gid" -ne "$EXPECTED_GID" ]]; then
        echo "Ownership mismatch:  $file (Expected: $EXPECTED_UID:$EXPECTED_GID, Found: $uid:$gid)"
        error_flag=1
    fi
done < <(find "$STACKABLE_DIR" -print0)

# Check permissions
while IFS= read -r -d '' file; do
    perms=$(stat -c "%A" "$file")
    owner_perms="${perms:1:3}"
    group_perms="${perms:4:3}"

    if [[ "$owner_perms" != "$group_perms" ]]; then
        echo "Permission mismatch: $file (Owner: $owner_perms, Group: $group_perms)"
        error_flag=1
    fi
done < <(find "$STACKABLE_DIR" -print0)

if [[ $error_flag -ne 0 ]]; then
    echo "Permission and Ownership checks failed!"
    exit 1
fi

echo "Permission and Ownership checks successful!"