[metadata.registries]
"oci.stackable.tech" = { namespace = "sdp" }

# Not part of SDP 25.7.0, but still required for hbase, hive, spark-k8s
[versions."3.3.6".local-images]
java-base = "11"
java-devel = "11"

[versions."3.3.6".build-arguments]
precompiled-hadoop-version = "3.3.6"
# Find the latest build timestamp here:
# https://oci.stackable.tech/harbor/projects/52/repositories/hadoop/artifacts-tab
precompiled_hadoop_ts = "1776412753"
async-profiler-version = "2.9"
jmx-exporter-version = "1.3.0"
hdfs-utils-version = "0.4.0"

[versions."3.4.2".local-images]
java-base = "11"
java-devel = "11"

[versions."3.4.2".build-arguments]
precompiled-hadoop-version = "3.4.2"
# Find the latest build timestamp here:
# https://oci.stackable.tech/harbor/projects/52/repositories/hadoop/artifacts-tab
precompiled_hadoop_ts = "1776412753"
async-profiler-version = "2.9"
jmx-exporter-version = "1.3.0"
hdfs-utils-version = "0.5.0"
