versions = [
    {
        "product": "3.3.4",
        "java-base": "11",
        "java-devel": "11",
        "async_profiler": "2.9",
        "jmx_exporter": "1.2.0",
        "protobuf": "3.7.1",
        "hdfs_utils": "0.4.0",
    },
    {
        "product": "3.3.6",
        "java-base": "11",
        "java-devel": "11",
        "async_profiler": "2.9",
        "jmx_exporter": "1.2.0",
        "protobuf": "3.7.1",
        "hdfs_utils": "0.4.0",
    },
    {
        "product": "3.4.0",
        "java-base": "11",
        "java-devel": "11",
        "async_profiler": "2.9",
        "jmx_exporter": "1.2.0",
        "protobuf": "3.7.1",
        "hdfs_utils": "0.4.0",
    },
    {
        "product": "3.4.1",
        "java-base": "11",
        "java-devel": "11",
        "async_profiler": "2.9",
        "jmx_exporter": "1.2.0",
        "protobuf": "3.7.1",
        "hdfs_utils": "0.4.1",
    },
]
