versions = [
    {
        "product": "2.9.3",
        "python": "3.9",
        "git_sync": "v4.4.1",
        "s3fs": "2024.9.0",
        "cyclonedx_bom": "6.0.0",
        "shared/statsd-exporter": "0.28.0",
        "tini": "0.19.0",
        "vector": "0.47.0",
        "uv": "0.7.8",
        "extras": "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino",
        "opa_auth_manager": "airflow-2",
    },
    {
        "product": "2.10.4",
        "python": "3.12",
        "git_sync": "v4.4.1",
        "s3fs": "2024.9.0",
        "cyclonedx_bom": "6.0.0",
        "shared/statsd-exporter": "0.28.0",
        "tini": "0.19.0",
        "vector": "0.47.0",
        "uv": "0.7.8",
        "extras": "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino",
        "opa_auth_manager": "airflow-2",
    },
    {
        "product": "2.10.5",
        "python": "3.12",
        "git_sync": "v4.4.1",
        "s3fs": "2024.9.0",
        "cyclonedx_bom": "6.0.0",
        "shared/statsd-exporter": "0.28.0",
        "tini": "0.19.0",
        "vector": "0.47.0",
        "uv": "0.7.8",
        "extras": "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino",
        "opa_auth_manager": "airflow-2",
    },
    {
        "product": "3.0.1",
        "python": "3.12",
        "git_sync": "v4.4.1",
        "s3fs": "2024.9.0",
        "cyclonedx_bom": "6.0.0",
        "shared/statsd-exporter": "0.28.0",
        "tini": "0.19.0",
        "vector": "0.47.0",
        "uv": "0.7.8",
        "extras": "async,amazon,celery,cncf-kubernetes,docker,elasticsearch,fab,ftp,grpc,hashicorp,http,ldap,google,microsoft-azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,trino",
        "opa_auth_manager": "airflow-3",
    },
]
