[versions."3.5.5".local-images]
"hadoop/hadoop" = "3.4.1" # Current Stackable LTS version. Source of the AWS and Azure artifacts to Spark's classpath.
java-base = "17"
java-devel = "17"
hbase = "2.6.2" # Current Stackable LTS version. Used to build the HBase connector.
vector = "0.49.0"

[versions."3.5.5".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.24.6" # https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.4.1
azure-storage-version = "7.0.1" # https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-azure/3.4.1
azure-keyvault-core-version = "1.0.0" # https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage/7.0.1
jackson-dataformat-xml-version = "2.15.2" # https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.5.2
stax2-api-version = "4.2.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
woodstox-core-version = "6.5.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1"

[versions."3.5.6".local-images]
"hadoop/hadoop" = "3.4.1" # Current Stackable LTS version. Source of the AWS and Azure artifacts to Spark's classpath.
java-base = "17"
java-devel = "17"
hbase = "2.6.2" # Current Stackable LTS version. Used to build the HBase connector.
vector = "0.49.0"

[versions."3.5.6".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.24.6" # https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.4.1
azure-storage-version = "7.0.1" # https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-azure/3.4.1
azure-keyvault-core-version = "1.0.0" # https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage/7.0.1
jackson-dataformat-xml-version = "2.15.2" # https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.5.2
stax2-api-version = "4.2.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
woodstox-core-version = "6.5.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1"

[versions."4.0.0".local-images]
"hadoop/hadoop" = "3.4.1"
java-base = "17"
java-devel = "17"
hbase = "2.6.2"
vector = "0.49.0"

[versions."4.0.0".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.24.6"
azure-storage-version = "7.0.1" # https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-azure/3.3.4
azure-keyvault-core-version = "1.0.0" # https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage/7.0.1
jackson-dataformat-xml-version = "2.15.2" # https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.5.1
stax2-api-version = "4.2.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
woodstox-core-version = "6.5.1" # https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.15.2
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1" # This is not supported in Spark 4 yet.
