[versions."3.5.6".local-images]
"hadoop/hadoop" = "3.4.2"
java-base = "17"
java-devel = "17"
hbase = "2.6.3"
vector = "0.49.0"

[versions."3.5.6".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.29.52"   # needs to match the version shipped by Hadoop
azure-storage-version = "7.0.1"           # needs to match the version shipped by Hadoop
azure-keyvault-core-version = "1.0.0"     # needs to match the version shipped by Hadoop
jackson-dataformat-xml-version = "2.15.2"
stax2-api-version = "4.2.1"
woodstox-core-version = "6.5.1"
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1"

[versions."3.5.7".local-images]
"hadoop/hadoop" = "3.4.2"
java-base = "17"
java-devel = "17"
hbase = "2.6.3"
vector = "0.49.0"

[versions."3.5.7".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.29.52"   # needs to match the version shipped by Hadoop
azure-storage-version = "7.0.1"           # needs to match the version shipped by Hadoop
azure-keyvault-core-version = "1.0.0"     # needs to match the version shipped by Hadoop
jackson-dataformat-xml-version = "2.15.2"
stax2-api-version = "4.2.1"
woodstox-core-version = "6.5.1"
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1"

[versions."4.0.1".local-images]
"hadoop/hadoop" = "3.4.2"
java-base = "17"
java-devel = "17"
hbase = "2.6.3"
vector = "0.49.0"

[versions."4.0.1".build-arguments]
python-version = "3.11"
aws-java-sdk-bundle-version = "2.29.52"   # needs to match the version shipped by Hadoop
azure-storage-version = "7.0.1"           # needs to match the version shipped by Hadoop
azure-keyvault-core-version = "1.0.0"     # needs to match the version shipped by Hadoop
jackson-dataformat-xml-version = "2.15.2"
stax2-api-version = "4.2.1"
woodstox-core-version = "6.5.1"
jmx-exporter-version = "1.3.0"
tini-version = "0.19.0"
hbase-connector-version = "1.0.1"         # This is not supported in Spark 4 yet.
