npmRegistryServer: "https://build-repo.stackable.tech/repository/npm-public/"

# By default, yarn retries failed HTTP requests after 3 seconds. We increase this to 50 seconds
# to spam the Nexus instance a little less. In combination with the timeout configured below, this
# should result in roughly 5 retries. See https://yarnpkg.com/configuration/yarnrc#httpRetry
httpRetry: 50

# By default, yarn times out after 1 minute. We increase this to 5 minutes to hopefully get less
# failing builds in CI. See https://yarnpkg.com/configuration/yarnrc#httpTimeout
httpTimeout: 5m
