versions = [
    {
        "product": "3.7.1",
        "java-base": "21",
        "java-devel": "21",
        "scala": "2.13",
        "kcat": "1.7.0",
        "opa_authorizer": "1.5.1",
        "jmx_exporter": "1.1.0",
    },
    {
        "product": "3.7.2",
        "java-base": "21",
        "java-devel": "21",
        "scala": "2.13",
        "kcat": "1.7.0",
        "opa_authorizer": "1.5.1",
        "jmx_exporter": "1.1.0",
    },
    {
        "product": "3.8.0",
        "java-base": "21",
        "java-devel": "21",
        "scala": "2.13",
        "kcat": "1.7.0",
        "opa_authorizer": "1.5.1",
        "jmx_exporter": "1.1.0",
    },
    {
        "product": "3.9.0",
        "java-base": "21",
        "java-devel": "21",
        "scala": "2.13",
        "kcat": "1.7.0",
        "opa_authorizer": "1.5.1",
        "jmx_exporter": "1.1.0",
    },
]
