#!/usr/bin/env bash
# shellcheck disable=SC2129
# Run this to auto-update the badges table in the readme

set -euo pipefail

# START: Configurables
AUTO_GENERATED_COMMENT="autogenerated by $0"
GITHUB_ACTION_URL_PREFIX="https://github.com/stackabletech/docker-images/actions/workflows"
COLS=4
# END: Configurables

LINK_SHORTCUTS=()
CURRENT_COLUMN=-1

BADGES_TMP=$(mktemp)
LINKS_TMP=$(mktemp)

echo "<!-- start:badges: $AUTO_GENERATED_COMMENT -->" >> "$BADGES_TMP"

# Print the empty headings
for _ in $(seq 0 $((COLS - 1))); do
  echo -n "| " >> "$BADGES_TMP"
done
echo "|" >> "$BADGES_TMP"

# Print the heading separator and alignments
for _ in $(seq 0 $((COLS - 1))); do
  echo -n "| -: " >> "$BADGES_TMP"
done
echo "|" >> "$BADGES_TMP"

for BUILD_WORKFLOW_FILE in .github/workflows/build_*.yaml; do
  CURRENT_COLUMN=$(( (CURRENT_COLUMN + 1) % COLS ))

  BUILD_WORKFLOW_NAME=$(yq -r '.name' "$BUILD_WORKFLOW_FILE")
  BUILD_WORKFLOW_BASENAME=$(basename "$BUILD_WORKFLOW_FILE")
  BUILD_WORKFLOW_URL="${GITHUB_ACTION_URL_PREFIX}/${BUILD_WORKFLOW_BASENAME}"
  BUILD_WORKFLOW_BADGE_URL="${BUILD_WORKFLOW_URL}/badge.svg"

  # Append the image and link shortcuts to be printed at the end
  LINK_SHORTCUTS+=("[${BUILD_WORKFLOW_NAME}]: ${BUILD_WORKFLOW_BADGE_URL}")
  LINK_SHORTCUTS+=("[${BUILD_WORKFLOW_BASENAME}]: ${BUILD_WORKFLOW_URL}")

  # Print the cells which contain the shortcuts to the image and link:
  # eg: [![Build Airflow]][build_airflow.yaml]
  echo -n "| [![${BUILD_WORKFLOW_NAME}]][${BUILD_WORKFLOW_BASENAME}] " >> "$BADGES_TMP"
  # Use this for debugging the grid (comment out the echo above):
  # echo -n "| x "

  # On the last column, cap it off
  if [ ${CURRENT_COLUMN} -eq $((COLS - 1)) ]; then
    echo -n "|" >> "$BADGES_TMP"
    echo >> "$BADGES_TMP"
  fi
done
echo -n "<!-- end:badges -->" >> "$BADGES_TMP"

# Print the image and link shortcuts. Eg:
# [Build Airflow]: https://github.com/stackabletech/docker-images/actions/workflows/build_airflow.yaml/badge.svg
# [build_airflow.yaml]: https://github.com/stackabletech/docker-images/actions/workflows/build_airflow.yaml
echo "<!-- start:links: $AUTO_GENERATED_COMMENT -->" >> "$LINKS_TMP"
printf '%s\n' "${LINK_SHORTCUTS[@]}" >> "$LINKS_TMP"
echo -n "<!-- end:links -->" >> "$LINKS_TMP"

BADGES_CONTENT=$(sed ':a;N;$!ba;s/\n/\\n/g' "$BADGES_TMP")
LINKS_CONTENT=$(sed ':a;N;$!ba;s/\n/\\n/g' "$LINKS_TMP")

README_TMP=$(mktemp)

awk "/^<!-- start:badges/{flag=1; print \"$BADGES_CONTENT\"} {if(!flag)print} /<!-- end:badges/{flag=0;next}" README.md > "$README_TMP"
cp "$README_TMP" README.md
awk "/^<!-- start:links/{flag=1; print \"$LINKS_CONTENT\"} {if(!flag)print} /<!-- end:links/{flag=0;next}" README.md > "$README_TMP"
cp "$README_TMP" README.md

# cleanup
rm "$BADGES_TMP" "$LINKS_TMP" "$README_TMP"
