---
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      upload:
        default: false
        type: boolean

env:
  RUST_VERSION: 1.87.0

jobs:
  build:
    name: Build boil-${{ inputs.target }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ inputs.target }}

      - name: Build Binary
        env:
          TARGET: ${{ inputs.target }}
        run: cargo build --target "$TARGET" --release --package boil

      - name: Rename Binary
        env:
          TARGET: ${{ inputs.target }}
        run: mv "target/$TARGET/release/boil" "boil-$TARGET"

      - name: Upload Artifact
        if: inputs.upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: boil-${{ inputs.target }}
