---
name: Build Kafka
run-name: |
  Build Kafka (attempt #${{ github.run_attempt }})

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2/2 * *' # https://crontab.guru/#0_0_2/2_*_*
  push:
    branches: [main]
    tags: ['*']
    paths:
      # To check dependencies, run this ( you will need to consider transitive dependencies)
      # bake --product PRODUCT -d | grep -v 'docker buildx bake' | jq '.target | keys[]'
      - kcat/**
      - kafka/**
      - kafka-testing-tools/**
      - vector/**
      - stackable-base/**
      - java-base/**
      - java-devel/**
      - .github/actions/**
      - .github/workflows/build_kafka.yaml
      - .github/workflows/reusable_build_image.yaml

jobs:
  build_image:
    name: Reusable Workflow
    uses: ./.github/workflows/reusable_build_image.yaml
    secrets:
      harbor-robot-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
      slack-token: ${{ secrets.SLACK_CONTAINER_IMAGE_TOKEN }}
    with:
      product-name: kafka
      sdp-version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.0-dev' }}
