---
name: Build ZooKeeper

env:
  PRODUCT_NAME: zookeeper

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - zookeeper/**
      - .github/actions/**
      - .github/workflows/dev_zookeeper.yaml
  pull_request:
    paths:
      - zookeeper/**
      - .github/**

jobs:
  generate_matrix:
    name: generate_matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: shard
        uses: ./.github/actions/shard
        with:
          product: ${{ env.PRODUCT_NAME }}
    outputs:
      versions: ${{ steps.shard.outputs.versions }}

  build:
    name: Build/Publish ${{ matrix.versions }}-${{ matrix.runner.arch }} Image
    needs: [generate_matrix]
    permissions:
      id-token: write
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ["ubuntu-latest", "ubicloud-standard-8-arm"]
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Product Image
        id: build
        uses: ./.github/actions/build
        with:
          product-name: ${{ env.PRODUCT_NAME }} # todo: how to handle workflow_dispatch (use product input)
          product-version: ${{ matrix.versions }}
      - name: Publish Product Image
        uses: ./.github/actions/publish-image
        with:
          product: ${{ env.PRODUCT_NAME }}
          image-name: ${{ steps.build.outputs.image-name }}
          image-version: ${{ steps.build.outputs.image-version }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
          harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}

  publish_manifests:
    name: Build/Publish ${{ matrix.versions }}-${{ matrix.runner.arch }} Manifests
    needs: [generate_matrix, build]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Product Manifest List
        uses: ./.github/actions/publish-manifest
        with:
          product: ${{ env.PRODUCT_NAME }} # todo: how to handle workflow_dispatch (use product input)
          image-version: ${{ matrix.versions }}-stackable0.0.0-dev
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
          harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
