---
  name: Mirror container image
  on:
    workflow_dispatch:
      inputs:
        component:
          type: choice
          description: Components available using this workflow
          options:
          - "registry.k8s.io/git-sync/git-sync"
          - "registry.k8s.io/sig-storage/csi-node-driver-registrar"
          - "registry.k8s.io/sig-storage/csi-provisioner"
        version:
          description: 'Version of the component selected from the dropdown'
          required: true

  env:
    DST_REGISTRY_HARBOR: oci.stackable.tech
    DST_REGISTRY_NEXUS: docker.stackable.tech
    DST_PROJECT_NEXUS: k8s
    DST_PROJECT_HARBOR: sdp

  jobs:
    mirror-image:
      name: Pull, Retag and Push dependencies for ${{ github.event.inputs.component }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          architecture:
            - "amd64"
            - "arm64"
      permissions:
        id-token: write
      outputs:
        REPO_DIGEST_OF_IMAGE_HARBOR_amd64: ${{ steps.push_harbor.outputs.REPO_DIGEST_OF_IMAGE_amd64 }}
        REPO_DIGEST_OF_IMAGE_HARBOR_arm64: ${{ steps.push_harbor.outputs.REPO_DIGEST_OF_IMAGE_arm64 }}
        REPO_DIGEST_OF_IMAGE_NEXUS_amd64: ${{ steps.push_nexus.outputs.REPO_DIGEST_OF_IMAGE_amd64 }}
        REPO_DIGEST_OF_IMAGE_NEXUS_arm64: ${{ steps.push_nexus.outputs.REPO_DIGEST_OF_IMAGE_arm64 }}
        PRODUCT: ${{ steps.map.outputs.PRODUCT }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        - name: Login to Stackable Harbor
          uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
          with:
            registry: ${{ env.DST_REGISTRY_HARBOR }}
            username: "robot$sdp+github-action-build"
            password: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
        - name: Login to Stackable Nexus
          uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
          with:
            registry: ${{ env.DST_REGISTRY_NEXUS }}
            username: github
            password: ${{ secrets.NEXUS_PASSWORD }}
        - name: Pull image from source registry
          uses: ./.github/actions/pull-components
          with:
            image: ${{ github.event.inputs.component }}:${{ github.event.inputs.version }}
            architecture: ${{ matrix.architecture }}
        # Mapping incoming source registry string of a product onto a product name.
        # This is necessary since customers might have repositories mirrored with the current image names
        # changing this would imply a 'breaking' change to those customers.
        # This can be mitigated by managing this change with customers together, wouldn't like to do it without a release.
        # TODO: With 24.11 check if component names can change.
        - name: Map components onto component names
          id: map
          run: |
            if [ "${{ github.event.inputs.component }}" == "registry.k8s.io/git-sync/git-sync" ]; then
              echo "PRODUCT="git-sync"" >> "$GITHUB_OUTPUT"
            elif [ "${{ github.event.inputs.component }}" == "registry.k8s.io/sig-storage/csi-node-driver-registrar" ]; then
              echo "PRODUCT="sig-storage/csi-node-driver-registrar"" >> "$GITHUB_OUTPUT"
            elif [ "${{ github.event.inputs.component }}" == "registry.k8s.io/sig-storage/csi-provisioner" ]; then
              echo "PRODUCT="sig-storage/csi-provisioner"" >> "$GITHUB_OUTPUT"
            else
              echo "Product not recognized"
              exit 1
            fi
        - name: Retag image
          run: |
            # Tagging the same image two times to push to Nexus and Harbor
            docker tag "${{ github.event.inputs.component }}:${{ github.event.inputs.version}}" "${{ env.DST_REGISTRY_HARBOR }}/${{ env.DST_PROJECT_HARBOR }}/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version}}-${{ matrix.architecture }}"
            docker tag "${{ github.event.inputs.component }}:${{ github.event.inputs.version}}" "${{ env.DST_REGISTRY_NEXUS }}/${{ env.DST_PROJECT_NEXUS }}/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version}}-${{ matrix.architecture }}"
        - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
        - name: Push image to harbor registry
          id: push_harbor
          uses: ./.github/actions/publish-component-image
          with:
            product: ${{ steps.map.outputs.PRODUCT }}
            version: ${{ github.event.inputs.version}}
            architecture: ${{ matrix.architecture }}
            registry: ${{ env.DST_REGISTRY_HARBOR }}
            project: ${{ env.DST_PROJECT_HARBOR }}
        - name: Push image to nexus registry
          id: push_nexus
          uses: ./.github/actions/publish-component-image
          with:
            product: ${{ steps.map.outputs.PRODUCT }}
            version: ${{ github.event.inputs.version}}
            architecture: ${{ matrix.architecture }}
            registry: ${{ env.DST_REGISTRY_NEXUS }}
            project: ${{ env.DST_PROJECT_NEXUS }}
    publish_manifest:
      name: Build/Publish ${{ github.event.inputs.component }} Manifests
      runs-on: ubuntu-latest
      needs: mirror-image
      permissions:
        id-token: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        - name: Build Product Manifest List ( Nexus )
          uses: ./.github/actions/publish-manifest
          with:
            product: ${{ needs.mirror-image.outputs.PRODUCT }}
            registry: $DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS
            image-version: ${{ github.event.inputs.version }}
            nexus-password: ${{ secrets.NEXUS_PASSWORD }}
            harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
            digest-arm: ${{ needs.mirror-image.outputs.REPO_DIGEST_OF_IMAGE_NEXUS_arm64}}
            digest-amd: ${{ needs.mirror-image.outputs.REPO_DIGEST_OF_IMAGE_NEXUS_amd64}}
        - name: Build Product Manifest List ( Harbor )
          uses: ./.github/actions/publish-manifest
          with:
            product: ${{ needs.mirror-image.outputs.PRODUCT }}
            image-version: ${{ github.event.inputs.version }}
            registry: $DST_REGISTRY_HARBOR/$DST_PROJECT_HARBOR
            nexus-password: ${{ secrets.NEXUS_PASSWORD }}
            harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
            digest-arm: ${{ needs.mirror-image.outputs.REPO_DIGEST_OF_IMAGE_HARBOR_arm64}}
            digest-amd: ${{ needs.mirror-image.outputs.REPO_DIGEST_OF_IMAGE_HARBOR_amd64}}
