---
name: pre-commit

on:
  pull_request:

permissions:
  contents: read

env:
  # Keep in sync with across other repos like operator-rs and operator-templating
  RUST_TOOLCHAIN_VERSION: "nightly-2026-07-01"
  HADOLINT_VERSION: "v2.14.0"
  PYTHON_VERSION: "3.14"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: stackabletech/actions/run-pre-commit@d0a8db3ba80e974b872c09cb5311f04e0e78582e # v0.16.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          hadolint: ${{ env.HADOLINT_VERSION }}
