---
name: prek

on:
  pull_request:

permissions:
  contents: read

env:
  # Keep in sync with across other repos like operator-rs and operator-templating
  RUST_TOOLCHAIN_VERSION: "nightly-2026-08-23"
  HADOLINT_VERSION: "v2.14.0"

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: stackabletech/actions/run-prek@0fe048f952bee522474903a925ea48dc706a0bb4 # v0.17.5
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          hadolint: ${{ env.HADOLINT_VERSION }}
