---
name: Test Build Images

on:
  workflow_dispatch:
  pull_request:
    branches: [main, 'release/*']
    # For now, we run on all paths, but if the products could be moved into a subdirectory, we could match on that
    # paths: []

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
