---
name: Sign container image
on:
  push:
    branches:
      - trying
#   workflow_dispatch:
#     inputs:
#       img:
#         description: 'Image to be signed (example: git-sync@sha256:22d1a4fa1e94cf9bddf2143e3349420572c997176ff818e59969b95a07267558)'
#         required: true

env:
  DST_REGISTRY: oci.stackable.tech
  DST_PROJECT: sdp

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # tag=v3.0.0
        with:
          registry: ${{ env.DST_REGISTRY }}
          username: "robot$sdp+github-action-build"
          password: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
      - uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # tag=v3.3.0
      - name: Sign image
        run: |
          # This generates a signature and publishes it to the registry, next to the image
          # Uses the keyless signing flow with Github Actions as identity provider
          cosign sign -y "$DST_REGISTRY/$DST_PROJECT/git-sync@sha256:fd95a95edec74e5a9d42d46045a6ef17dcfb39e623f711acbf5ce4fe25a735e2"
