[versions."1.1.2".local-images]
java-base = "11"
java-devel = "11"

[versions."1.1.2".build-arguments]
jmx-exporter-version = "1.3.0"

[versions."1.1.3".local-images]
java-base = "11"
java-devel = "11"

[versions."1.1.3".build-arguments]
jmx-exporter-version = "1.3.0"
